default:
  image: python:3.9-buster
  before_script:
  - python --version
  - pip install .[extras]
  - pip install pytest
  - pip install pdoc
  - pip install git+https://github.com/cat-cfs/libcbm_py.git@1.x
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/eu_cbm/eu_cbm_aidb.git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/eu_cbm/eu_cbm_data.git
  # Tell eu_cbm_hat where the data are located
  - export EU_CBM_DATA="$CI_PROJECT_DIR/eu_cbm_data/"
  - export EU_CBM_AIDB="$CI_PROJECT_DIR/eu_cbm_aidb/"
  - python scripts/setup/aidb_symlink.py

stages:
  - document
  - test

pages:
  stage: document
  script:
  - pdoc -o docs ./eu_cbm_hat
  artifacts:
    paths:
    - docs/eu_cbm_hat
  only:
  - main
  interruptible: true

libcbm_run:
  stage: test
  script:
    # The following test depends on ZZ data stored in the (private) eu_cbm_data repository
    - python scripts/running/run_zz.py
    - pytest --junitxml=report.xml eu_cbm_hat
    # The following test doesn't depend on the eu_cbm_data repository.
    # It uses ZZ data stored in the (public) eu_cbm_hat package.
    - python scripts/running/run_zz_in_temp_dir_without_eu_cbm_data.py
  artifacts:
    when: always
    reports:
      junit: report.xml

