default:
  image: python:buster
  before_script:
  - python --version
  - pip install -r requirements.txt
  - git clone https://github.com/cat-cfs/libcbm_py.git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/libcbm/libcbm_aidb.git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/libcbm/libcbm_data.git
  - ls
  - ls $CI_PROJECT_DIR
  - export PYTHONPATH="$CI_PROJECT_DIR/libcbm_py/":$PYTHONPATH
  - export PYTHONPATH="$CI_PROJECT_DIR/libcbm_runner/":$PYTHONPATH
  - export LIBCBM_DATA="$CI_PROJECT_DIR/libcbm_data/"

stages:
  - test

libcbm_run:
  stage: test
  script: 
    - python scripts/setup/aidb_symlink.py
    - python scripts/running/run_zz.py
