default:
  image: python:buster
  before_script:
  - python --version
  - pip install -r requirements.txt
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/libcbm/libcbm_aidb.git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bioeconomy/libcbm/libcbm_data.git
  - ls
  - ls $HOME
  - export PYTHONPATH="$HOME/libcbm_py/":$PYTHONPATH
  - export PYTHONPATH="$HOME/libcbm_runner/":$PYTHONPATH
  - export LIBCBM_DATA="$HOME/libcbm_data/"

stages:
  - test

libcbm_run:
  stage: test
  script: 
    - python scripts/setup/aidb_symlink.py
    - python scripts/running/run_zz.py
